---
- name: add weupd8team repo
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=true

- name: agree Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install java
  apt: package=oracle-java{{ java_version }}-installer state=latest update_cache=true

- name: set default java version
  apt: package=oracle-java{{ java_version }}-set-default state=latest update_cache=true
